name: Oppdater Fotobokser

on:
  schedule:
    - cron: '0 3 * * 1' # Kjører hver mandag kl 03:00
  workflow_dispatch:      # Lar deg starte den manuelt med en knapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v3

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer biblioteker
        run: pip install requests

      - name: Kjor skriptet
        run: python hent_fotobokser.py

      - name: Lagre endringer
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add ATK.csv
          git commit -m "Automatisk oppdatering av ATK.csv" || exit 0
          git push
